// flow-typed signature: b18024ede9b4326672b702ac6478722e
// flow-typed version: <<STUB>>/neo4j_v^2.0.0-RC2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neo4j'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'neo4j' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neo4j/lib-new/Constraint' {
  declare module.exports: any;
}

declare module 'neo4j/lib-new/errors' {
  declare module.exports: any;
}

declare module 'neo4j/lib-new/exports' {
  declare module.exports: any;
}

declare module 'neo4j/lib-new/GraphDatabase' {
  declare module.exports: any;
}

declare module 'neo4j/lib-new/Index' {
  declare module.exports: any;
}

declare module 'neo4j/lib-new/Node' {
  declare module.exports: any;
}

declare module 'neo4j/lib-new/Relationship' {
  declare module.exports: any;
}

declare module 'neo4j/lib-new/Transaction' {
  declare module.exports: any;
}

declare module 'neo4j/lib-new/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neo4j/lib-new/Constraint.js' {
  declare module.exports: $Exports<'neo4j/lib-new/Constraint'>;
}
declare module 'neo4j/lib-new/errors.js' {
  declare module.exports: $Exports<'neo4j/lib-new/errors'>;
}
declare module 'neo4j/lib-new/exports.js' {
  declare module.exports: $Exports<'neo4j/lib-new/exports'>;
}
declare module 'neo4j/lib-new/GraphDatabase.js' {
  declare module.exports: $Exports<'neo4j/lib-new/GraphDatabase'>;
}
declare module 'neo4j/lib-new/Index.js' {
  declare module.exports: $Exports<'neo4j/lib-new/Index'>;
}
declare module 'neo4j/lib-new/Node.js' {
  declare module.exports: $Exports<'neo4j/lib-new/Node'>;
}
declare module 'neo4j/lib-new/Relationship.js' {
  declare module.exports: $Exports<'neo4j/lib-new/Relationship'>;
}
declare module 'neo4j/lib-new/Transaction.js' {
  declare module.exports: $Exports<'neo4j/lib-new/Transaction'>;
}
declare module 'neo4j/lib-new/utils.js' {
  declare module.exports: $Exports<'neo4j/lib-new/utils'>;
}
